# These are supported funding model platforms

github: [pabitra-kumar]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: pabitra-kumar # Replace with your Patreon username
custom: https://www.buymeacoffee.com/pabitrakumar00
